<?php
// core/lib/lucide-icons.php — generated by tools/extract-lucide.php from lucide@0.469.0.
// Re-run when adding an icon. Source data: ISC license (https://lucide.dev).
// Edited by hand at your peril — regen is the supported workflow.

return array (
  'zap' => 
  array (
    0 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M4 14a1 1 0 0 1-.78-1.63l9.9-10.2a.5.5 0 0 1 .86.46l-1.92 6.02A1 1 0 0 0 13 10h7a1 1 0 0 1 .78 1.63l-9.9 10.2a.5.5 0 0 1-.86-.46l1.92-6.02A1 1 0 0 0 11 14z',
      ),
    ),
  ),
  'arrow-right' => 
  array (
    0 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M5 12h14',
      ),
    ),
    1 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'm12 5 7 7-7 7',
      ),
    ),
  ),
  'arrow-left' => 
  array (
    0 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'm12 19-7-7 7-7',
      ),
    ),
    1 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M19 12H5',
      ),
    ),
  ),
  'check' => 
  array (
    0 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M20 6 9 17l-5-5',
      ),
    ),
  ),
  'chevron-down' => 
  array (
    0 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'm6 9 6 6 6-6',
      ),
    ),
  ),
  'calendar-days' => 
  array (
    0 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M8 2v4',
      ),
    ),
    1 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M16 2v4',
      ),
    ),
    2 => 
    array (
      'tag' => 'rect',
      'attrs' => 
      array (
        'width' => '18',
        'height' => '18',
        'x' => '3',
        'y' => '4',
        'rx' => '2',
      ),
    ),
    3 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M3 10h18',
      ),
    ),
    4 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M8 14h.01',
      ),
    ),
    5 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M12 14h.01',
      ),
    ),
    6 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M16 14h.01',
      ),
    ),
    7 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M8 18h.01',
      ),
    ),
    8 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M12 18h.01',
      ),
    ),
    9 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M16 18h.01',
      ),
    ),
  ),
  'sparkles' => 
  array (
    0 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M9.937 15.5A2 2 0 0 0 8.5 14.063l-6.135-1.582a.5.5 0 0 1 0-.962L8.5 9.936A2 2 0 0 0 9.937 8.5l1.582-6.135a.5.5 0 0 1 .963 0L14.063 8.5A2 2 0 0 0 15.5 9.937l6.135 1.581a.5.5 0 0 1 0 .964L15.5 14.063a2 2 0 0 0-1.437 1.437l-1.582 6.135a.5.5 0 0 1-.963 0z',
      ),
    ),
    1 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M20 3v4',
      ),
    ),
    2 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M22 5h-4',
      ),
    ),
    3 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M4 17v2',
      ),
    ),
    4 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M5 18H3',
      ),
    ),
  ),
  'users' => 
  array (
    0 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2',
      ),
    ),
    1 => 
    array (
      'tag' => 'circle',
      'attrs' => 
      array (
        'cx' => '9',
        'cy' => '7',
        'r' => '4',
      ),
    ),
    2 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M22 21v-2a4 4 0 0 0-3-3.87',
      ),
    ),
    3 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M16 3.13a4 4 0 0 1 0 7.75',
      ),
    ),
  ),
  'message-square-text' => 
  array (
    0 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z',
      ),
    ),
    1 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M13 8H7',
      ),
    ),
    2 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M17 12H7',
      ),
    ),
  ),
  'file-output' => 
  array (
    0 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M14 2v4a2 2 0 0 0 2 2h4',
      ),
    ),
    1 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M4 7V4a2 2 0 0 1 2-2 2 2 0 0 0-2 2',
      ),
    ),
    2 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M4.063 20.999a2 2 0 0 0 2 1L18 22a2 2 0 0 0 2-2V7l-5-5H6',
      ),
    ),
    3 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'm5 11-3 3',
      ),
    ),
    4 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'm5 17-3-3h10',
      ),
    ),
  ),
  'layout-template' => 
  array (
    0 => 
    array (
      'tag' => 'rect',
      'attrs' => 
      array (
        'width' => '18',
        'height' => '7',
        'x' => '3',
        'y' => '3',
        'rx' => '1',
      ),
    ),
    1 => 
    array (
      'tag' => 'rect',
      'attrs' => 
      array (
        'width' => '9',
        'height' => '7',
        'x' => '3',
        'y' => '14',
        'rx' => '1',
      ),
    ),
    2 => 
    array (
      'tag' => 'rect',
      'attrs' => 
      array (
        'width' => '5',
        'height' => '7',
        'x' => '16',
        'y' => '14',
        'rx' => '1',
      ),
    ),
  ),
  'building-2' => 
  array (
    0 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M6 22V4a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v18Z',
      ),
    ),
    1 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M6 12H4a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2h2',
      ),
    ),
    2 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M18 9h2a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2h-2',
      ),
    ),
    3 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M10 6h4',
      ),
    ),
    4 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M10 10h4',
      ),
    ),
    5 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M10 14h4',
      ),
    ),
    6 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M10 18h4',
      ),
    ),
  ),
  'calendar-plus' => 
  array (
    0 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M8 2v4',
      ),
    ),
    1 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M16 2v4',
      ),
    ),
    2 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M21 13V6a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h8',
      ),
    ),
    3 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M3 10h18',
      ),
    ),
    4 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M16 19h6',
      ),
    ),
    5 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M19 16v6',
      ),
    ),
  ),
  'wand-sparkles' => 
  array (
    0 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'm21.64 3.64-1.28-1.28a1.21 1.21 0 0 0-1.72 0L2.36 18.64a1.21 1.21 0 0 0 0 1.72l1.28 1.28a1.2 1.2 0 0 0 1.72 0L21.64 5.36a1.2 1.2 0 0 0 0-1.72',
      ),
    ),
    1 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'm14 7 3 3',
      ),
    ),
    2 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M5 6v4',
      ),
    ),
    3 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M19 14v4',
      ),
    ),
    4 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M10 2v2',
      ),
    ),
    5 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M7 8H3',
      ),
    ),
    6 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M21 16h-4',
      ),
    ),
    7 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M11 3H9',
      ),
    ),
  ),
  'send' => 
  array (
    0 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M14.536 21.686a.5.5 0 0 0 .937-.024l6.5-19a.496.496 0 0 0-.635-.635l-19 6.5a.5.5 0 0 0-.024.937l7.93 3.18a2 2 0 0 1 1.112 1.11z',
      ),
    ),
    1 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'm21.854 2.147-10.94 10.939',
      ),
    ),
  ),
  'user' => 
  array (
    0 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2',
      ),
    ),
    1 => 
    array (
      'tag' => 'circle',
      'attrs' => 
      array (
        'cx' => '12',
        'cy' => '7',
        'r' => '4',
      ),
    ),
  ),
  'briefcase' => 
  array (
    0 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M16 20V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16',
      ),
    ),
    1 => 
    array (
      'tag' => 'rect',
      'attrs' => 
      array (
        'width' => '20',
        'height' => '14',
        'x' => '2',
        'y' => '6',
        'rx' => '2',
      ),
    ),
  ),
  'building' => 
  array (
    0 => 
    array (
      'tag' => 'rect',
      'attrs' => 
      array (
        'width' => '16',
        'height' => '20',
        'x' => '4',
        'y' => '2',
        'rx' => '2',
        'ry' => '2',
      ),
    ),
    1 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M9 22v-4h6v4',
      ),
    ),
    2 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M8 6h.01',
      ),
    ),
    3 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M16 6h.01',
      ),
    ),
    4 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M12 6h.01',
      ),
    ),
    5 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M12 10h.01',
      ),
    ),
    6 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M12 14h.01',
      ),
    ),
    7 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M16 10h.01',
      ),
    ),
    8 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M16 14h.01',
      ),
    ),
    9 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M8 10h.01',
      ),
    ),
    10 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M8 14h.01',
      ),
    ),
  ),
  'bot' => 
  array (
    0 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M12 8V4H8',
      ),
    ),
    1 => 
    array (
      'tag' => 'rect',
      'attrs' => 
      array (
        'width' => '16',
        'height' => '12',
        'x' => '4',
        'y' => '8',
        'rx' => '2',
      ),
    ),
    2 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M2 14h2',
      ),
    ),
    3 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M20 14h2',
      ),
    ),
    4 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M15 13v2',
      ),
    ),
    5 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M9 13v2',
      ),
    ),
  ),
  'mail' => 
  array (
    0 => 
    array (
      'tag' => 'rect',
      'attrs' => 
      array (
        'width' => '20',
        'height' => '16',
        'x' => '2',
        'y' => '4',
        'rx' => '2',
      ),
    ),
    1 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'm22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7',
      ),
    ),
  ),
  'phone' => 
  array (
    0 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z',
      ),
    ),
  ),
  'settings' => 
  array (
    0 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z',
      ),
    ),
    1 => 
    array (
      'tag' => 'circle',
      'attrs' => 
      array (
        'cx' => '12',
        'cy' => '12',
        'r' => '3',
      ),
    ),
  ),
  'search' => 
  array (
    0 => 
    array (
      'tag' => 'circle',
      'attrs' => 
      array (
        'cx' => '11',
        'cy' => '11',
        'r' => '8',
      ),
    ),
    1 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'm21 21-4.3-4.3',
      ),
    ),
  ),
  'plus' => 
  array (
    0 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M5 12h14',
      ),
    ),
    1 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M12 5v14',
      ),
    ),
  ),
  'x' => 
  array (
    0 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M18 6 6 18',
      ),
    ),
    1 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'm6 6 12 12',
      ),
    ),
  ),
  'info' => 
  array (
    0 => 
    array (
      'tag' => 'circle',
      'attrs' => 
      array (
        'cx' => '12',
        'cy' => '12',
        'r' => '10',
      ),
    ),
    1 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M12 16v-4',
      ),
    ),
    2 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M12 8h.01',
      ),
    ),
  ),
  'triangle-alert' => 
  array (
    0 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'm21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3',
      ),
    ),
    1 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M12 9v4',
      ),
    ),
    2 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M12 17h.01',
      ),
    ),
  ),
  'star' => 
  array (
    0 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M11.525 2.295a.53.53 0 0 1 .95 0l2.31 4.679a2.123 2.123 0 0 0 1.595 1.16l5.166.756a.53.53 0 0 1 .294.904l-3.736 3.638a2.123 2.123 0 0 0-.611 1.878l.882 5.14a.53.53 0 0 1-.771.56l-4.618-2.428a2.122 2.122 0 0 0-1.973 0L6.396 21.01a.53.53 0 0 1-.77-.56l.881-5.139a2.122 2.122 0 0 0-.611-1.879L2.16 9.795a.53.53 0 0 1 .294-.906l5.165-.755a2.122 2.122 0 0 0 1.597-1.16z',
      ),
    ),
  ),
  'trash' => 
  array (
    0 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M3 6h18',
      ),
    ),
    1 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6',
      ),
    ),
    2 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2',
      ),
    ),
  ),
  'download' => 
  array (
    0 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4',
      ),
    ),
    1 => 
    array (
      'tag' => 'polyline',
      'attrs' => 
      array (
        'points' => '7 10 12 15 17 10',
      ),
    ),
    2 => 
    array (
      'tag' => 'line',
      'attrs' => 
      array (
        'x1' => '12',
        'x2' => '12',
        'y1' => '15',
        'y2' => '3',
      ),
    ),
  ),
  'upload' => 
  array (
    0 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4',
      ),
    ),
    1 => 
    array (
      'tag' => 'polyline',
      'attrs' => 
      array (
        'points' => '17 8 12 3 7 8',
      ),
    ),
    2 => 
    array (
      'tag' => 'line',
      'attrs' => 
      array (
        'x1' => '12',
        'x2' => '12',
        'y1' => '3',
        'y2' => '15',
      ),
    ),
  ),
  'pencil' => 
  array (
    0 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z',
      ),
    ),
    1 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'm15 5 4 4',
      ),
    ),
  ),
  'copy' => 
  array (
    0 => 
    array (
      'tag' => 'rect',
      'attrs' => 
      array (
        'width' => '14',
        'height' => '14',
        'x' => '8',
        'y' => '8',
        'rx' => '2',
        'ry' => '2',
      ),
    ),
    1 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2',
      ),
    ),
  ),
  'link' => 
  array (
    0 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71',
      ),
    ),
    1 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71',
      ),
    ),
  ),
  'lock' => 
  array (
    0 => 
    array (
      'tag' => 'rect',
      'attrs' => 
      array (
        'width' => '18',
        'height' => '11',
        'x' => '3',
        'y' => '11',
        'rx' => '2',
        'ry' => '2',
      ),
    ),
    1 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M7 11V7a5 5 0 0 1 10 0v4',
      ),
    ),
  ),
  'eye' => 
  array (
    0 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0',
      ),
    ),
    1 => 
    array (
      'tag' => 'circle',
      'attrs' => 
      array (
        'cx' => '12',
        'cy' => '12',
        'r' => '3',
      ),
    ),
  ),
  'menu' => 
  array (
    0 => 
    array (
      'tag' => 'line',
      'attrs' => 
      array (
        'x1' => '4',
        'x2' => '20',
        'y1' => '12',
        'y2' => '12',
      ),
    ),
    1 => 
    array (
      'tag' => 'line',
      'attrs' => 
      array (
        'x1' => '4',
        'x2' => '20',
        'y1' => '6',
        'y2' => '6',
      ),
    ),
    2 => 
    array (
      'tag' => 'line',
      'attrs' => 
      array (
        'x1' => '4',
        'x2' => '20',
        'y1' => '18',
        'y2' => '18',
      ),
    ),
  ),
  'chevron-up' => 
  array (
    0 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'm18 15-6-6-6 6',
      ),
    ),
  ),
  'chevron-left' => 
  array (
    0 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'm15 18-6-6 6-6',
      ),
    ),
  ),
  'chevron-right' => 
  array (
    0 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'm9 18 6-6-6-6',
      ),
    ),
  ),
  'arrow-up' => 
  array (
    0 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'm5 12 7-7 7 7',
      ),
    ),
    1 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M12 19V5',
      ),
    ),
  ),
  'arrow-down' => 
  array (
    0 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'M12 5v14',
      ),
    ),
    1 => 
    array (
      'tag' => 'path',
      'attrs' => 
      array (
        'd' => 'm19 12-7 7-7-7',
      ),
    ),
  ),
);
